### ISSUE TITLE
Can't start project

### ISSUE THREAD

**Issue by TotallWAR** [vip-git/react-ssr-advanced-seed#113]
Hello!
I'm finding nest js react ssr boilerplate and found this repo.
I cloned last master release and can't event start the project. A lot of depencies are not resolved, some packages are not in package json.

Could you provide some more info about starting of your project please?

**Comment by vip-git** [comment]
Hi @TotallWAR - You can try now by cloning fresh copy of this repo.

Currently - this is work in progress as i am working on getting the Mobile version integrated with react native. 

Thanks - V
